import os

dirs = [
    "app",
    "app/api",
    "app/api/v1",
    "app/api/websocket",
    "app/services",
    "app/ai",
    "app/repositories",
    "app/models",
    "app/models/database",
    "app/models/schemas",
    "app/core",
    "app/db",
    "app/db/migrations",
    "app/tasks",
    "app/utils",
    "tests",
    "tests/unit",
    "tests/integration",
    "alembic",
    "docker"
]

files = [
    "app/__init__.py",
    "app/main.py",
    "app/config.py",
    "app/dependencies.py",
    "app/api/__init__.py",
    "app/api/v1/__init__.py",
    "app/api/v1/router.py",
    "app/api/v1/auth.py",
    "app/api/v1/profile.py",
    "app/api/v1/interviews.py",
    "app/api/v1/analytics.py",
    "app/api/v1/streaks.py",
    "app/api/v1/recommendations.py",
    "app/api/v1/resumes.py",
    "app/api/websocket/__init__.py",
    "app/api/websocket/interview_ws.py",
    "app/services/__init__.py",
    "app/services/auth_service.py",
    "app/services/interview_service.py",
    "app/services/evaluation_service.py",
    "app/services/analytics_service.py",
    "app/services/recommendation_service.py",
    "app/services/streak_service.py",
    "app/services/resume_service.py",
    "app/ai/__init__.py",
    "app/ai/llm_engine.py",
    "app/ai/stt_engine.py",
    "app/ai/embedding_engine.py",
    "app/ai/confidence_engine.py",
    "app/ai/grammar_engine.py",
    "app/ai/adaptive_engine.py",
    "app/ai/evaluation_engine.py",
    "app/ai/recommendation_engine.py",
    "app/repositories/__init__.py",
    "app/repositories/base_repository.py",
    "app/repositories/user_repository.py",
    "app/repositories/interview_repository.py",
    "app/repositories/question_repository.py",
    "app/repositories/answer_repository.py",
    "app/repositories/analytics_repository.py",
    "app/models/__init__.py",
    "app/models/database/__init__.py",
    "app/models/database/user.py",
    "app/models/database/interview.py",
    "app/models/database/question.py",
    "app/models/database/analytics.py",
    "app/models/schemas/__init__.py",
    "app/models/schemas/auth_schema.py",
    "app/models/schemas/interview_schema.py",
    "app/models/schemas/analytics_schema.py",
    "app/core/__init__.py",
    "app/core/security.py",
    "app/core/exceptions.py",
    "app/core/middleware.py",
    "app/core/events.py",
    "app/db/__init__.py",
    "app/db/session.py",
    "app/db/redis.py",
    "app/tasks/__init__.py",
    "app/tasks/celery_app.py",
    "app/tasks/evaluation_tasks.py",
    "app/tasks/analytics_tasks.py",
    "app/utils/__init__.py",
    "app/utils/file_handler.py",
    "app/utils/email_sender.py",
    "app/utils/logger.py",
    "tests/__init__.py",
    "tests/unit/__init__.py",
    "tests/integration/__init__.py",
    "tests/conftest.py",
    "requirements.txt",
    "Dockerfile",
]

for d in dirs:
    os.makedirs(d, exist_ok=True)

for f in files:
    with open(f, "w") as file:
        pass

print("Scaffold complete.")
