"""gamification fields

Revision ID: caa07af041e2
Revises: b0c7b4f56ceb
Create Date: 2026-07-28 22:41:03.611513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa07af041e2'
down_revision: Union[str, None] = 'b0c7b4f56ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('longest_streak', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('last_practice_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('badges', sa.JSON(), nullable=True))
    op.add_column('skill_progress', sa.Column('xp', sa.Integer(), nullable=True))
    op.add_column('skill_progress', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_progress', 'level')
    op.drop_column('skill_progress', 'xp')
    op.drop_column('profiles', 'badges')
    op.drop_column('profiles', 'last_practice_date')
    op.drop_column('profiles', 'longest_streak')
    op.drop_column('profiles', 'current_streak')
    # ### end Alembic commands ###
